# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Jabber
version:      2.0
version_from: lib/Net/Jabber.pm
installdirs:  site
requires:
    Net::XMPP:                     1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
